### ISSUE TITLE
Using Python/Jython in custom facets

### ISSUE THREAD

**Issue by richyvk** [data-lessons/library-openrefine-DEPRECATED#145]
I think it would be good to mention that you can do this, and maybe have a very short example. There seems to be very little written about this generally from what I can tell. Today I learned as long as you add a return statement you are good to go in using Jython statements to facet, but it took me a while to find even this basic info.

**Comment by richyvk** [comment]
Actual;l;y, mayeb the return thing was my fault - I think I deleted it - seems it does get added automatically when you do a custom facet

**Comment by ostephens** [comment]
I think this could work as part of the more advanced OR lesson.
A good resource for getting started with Jython in OR is https://github.com/OpenRefine/OpenRefine/wiki/Jython which includes information on how to add and use Python and Java libraries by using Jython in OR

**Comment by richyvk** [comment]
You're right of course Owen. It is a bit advanced perhaps. Thanks for the link, that's the page I found that helped me :)

It's really pretty amazing what you can do with OR and Jython isn't it!

I am planning on teaching the OR lesson later int he year, I might mention the capability, and maybe do a simple demo. If I do I'll fork the lesson and make some additions for future consideration.

**Comment by ostephens** [comment]
Thanks @richyvk - let us know how it goes :)

**Comment by evanwill** [comment]
I have a lesson coming out that uses Jython in Refine to implement a POST request, which really extends the possibilities for APIs or web scraping (I will add the link here when it's published). In general Jython is great if you already have a handy way in Python to do what you want, but if you are spending a lot of time messing around with it, you are better off just working in Python directly, since that is not the strength of Refine.

**Comment by evanwill** [comment]
here is my Programming Historian lesson, the last section ("Example 3: Advanced APIs") is about using Jython for HTTP Post request: 
<https://programminghistorian.org/lessons/fetch-and-parse-data-with-openrefine>
