### ISSUE TITLE
VIAF exercise

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-openrefine-DEPRECATED#167]
Re https://github.com/data-lessons/library-openrefine/blob/gh-pages/_episodes/08-looking-up-data.md

So I love the VIAF exercise. It really shows the power of Refine to add data to a dataset. But LC Padova feedback suggests it is too hard. I suspect there are too many new things here for something at the end of a day. Perhaps the big text block can be broken down into more clearly defined chunks, such as:
- use a reconciliation service (up to 'start reconciling')
- working with outputs of a reconciliation service (looking at the new facets)
- adding new data based on a reconciliation service (the new column bit)

**Comment by weaverbel** [comment]
I agree that this is too much - people just get absolutely dazed by the time they get to CrossRef  - best to leave them wanting more and giving them things to explore independently than to keep piling more stuff on and then they leave feeling battered and broken down  @drjwbaker @ostephens @ccronje

**Comment by drjwbaker** [comment]
I actually didn't do both. Just VIAF. I see this advanced section as an either/or.

**Comment by pitviper6** [comment]
I think if we break it into chunks, so that the instructor can have some flexibility about where to stop, it would be great. Every audience is different (some are baffled by this section, some want even more once we've done the reconciliation part if you've got a room full of catalogers who have worked with linked open data).  And if you have a two day workshop where you get an entire day for Open Refine, you have time to get to this point without being overwhelming. So chunking it would allow for any scenario.

**Comment by ostephens** [comment]
Agreed - splitting up this part would be great - already have an issue for this #16

**Comment by drjwbaker** [comment]
I'll leave it in your capable hands then! Happy to review if and when I'm needed :)
