### ISSUE TITLE
Add an exercise to demonstrate GREL 'replace' function

### ISSUE THREAD

**Issue by ostephens** [data-lessons/library-openrefine-DEPRECATED#38]
value.replace() is a simple but powerful function, it would be good to have an exercise to demonstrate this

**Comment by drjwbaker** [comment]
Are you happy to take this on or looking for a co-author?

**Comment by weaverbel** [comment]
@ostephens @drjwbaker I am going to teach this tomorrow so an easy place to slot in in with the existing data set and lessons  is using `value.replace` to change the pipe to a colon before you split author names into separate cells. GREL is Edit cells -> Transform `value.replace("|", ":")` Then when you split the cells in the next exercise you just say the separator is a colon now instead of a pipe.

I also think it is good to show them how to join columns (e.g. for combining first and last names which they will often want to do for contact lists) so I am going to show them that by putting the citation back into one column after splitting it initially
Edit cells -> Transform: `cells['Citation 1'].value + ' ' + cells['Citation 2'].value + ' ' + cells['Citation 3'].value + ' ' + cells['Citation 4'].value`
These wouldn't take long to teach but from my Adelaide feedback, these definitely had a wow factor. They seem simple but they are hard to do in Excel etc.

**Comment by weaverbel** [comment]
@ostephens @drjwbaker Are you okay with me adding a bit of value.replace() to the existing lesson? Happy to do that if you agree - but people do like to know that's possible.

**Comment by ostephens** [comment]
I'd like to see a more meaningful use of the replace function if we can manage it. Also, putting it at this point means leaping to the concept of a 'transform' before the right point in the lesson (transforms aren't introduced until the next episode).

I'll have a look and think

**Comment by ostephens** [comment]
I've done a quick review of the data as it currently stands and I can't see any very obvious use of the 'replace' function that makes sense. In order to demonstrate the replace function I think we need to introduce some inconsistency to the example data set that can be fixed using 'replace'.

A simple suggestion: if we edited some of the ISSNs that contain an 'X' to contain a lowercase 'x' instead, we could use replace to fix this problem.

Open to other suggestions but for me this needs to:

1) Be a meaningful demonstration
2) Fit immediately before or after the current Exercise 8

If this proposal sounds OK I'm happy to make the necessary modifications then do a pull request for review

**Comment by drjwbaker** [comment]
Seems sensible. Thanks.

**Comment by weaverbel** [comment]
That's fine @ostephens - it's just I'd like to see it somewhere in there as people would find it useful. Your idea sounds a good one.

**Comment by ccronje** [comment]
@ostephens I like your idea of changing the dataset for ISSN to demo replace. I taught this lesson yesterday and another example came to mind. After Exercise 8 (converting to Titlecase) - there are words you wouldn't want in title case e.g. **Path Finder Process Validation Of Moist Heat Sterilizer In Parentral Manufacturing Unit** versus **Path Finder Process Validation of Moist Heat Sterilizer in Parentral Manufacturing Unit**. At first I tried `value.replace("Of", "of").replace("In", "in")` etc. stringing along a few replace functions to demo. A learner spotted that "In" incorrectly changed "instrumental" and "incomplete" in one of the titles - which was great because it presented an extra problem to solve e.g. surrounding the words with whitespace or using regex word boundaries.

**Comment by weaverbel** [comment]
I can definitely say that librarians are keen to see a working example of GREL value.replace @ostephens @ccronje - @pitviper6 and I showed them a simple one at MIT. I agree it needs to be meaningful but it would be good to create one that we could use.

I also do a join columns/split columns example!

**Comment by ccronje** [comment]
New smaller episode http://data-lessons.github.io/library-openrefine/06-basic-functions-IV/ could be a good place to exercise splitting/joining columns.

**Comment by ccronje** [comment]
New smaller episode http://data-lessons.github.io/library-openrefine/06-basic-functions-IV/ might also be a good place to do a VLOOKUP type exercise.

**Comment by pitviper6** [comment]
I have been thinking about this, and I've been trying to come up with an example that isn't more easily done using faceting or clustering, or that finds/replaces in a way that makes more sense in a GREL use.

Perhaps finding an example where you want to change at least two instances instead of just one? What is the best context for using the GREL replace function vis-a-vis the other ways you can replace in OR?

**Comment by ostephens** [comment]
I've submitted a PR #129 to change a couple of trailing 'x' to lowercase. We can then add a demonstration of 'replace' changing the lowercase x to an uppercase X.

If we want this can be combined with a custom text facet on the ISSN col to find the relevant rows: 
`value.endsWith("x")`

**Comment by ccronje** [comment]
Thanks @ostephens, I've merged the PR and will keep this open for any further discussion about new exercise.
