### ISSUE TITLE
Modify Exercise 10 to include new columns for family & first name(s) using GREL

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-openrefine-DEPRECATED#64]
Modify Exercise 10 in episode http://data-lessons.github.io/library-openrefine/04-basic-functions-II/ to include the creation of new columns for family name and first name(s), using a GREL transformation.

(from discussion https://github.com/data-lessons/library-openrefine/issues/14#issuecomment-223933396)

**Comment by ccronje** [comment]
@ostephens is this meant to go at the end of the current exercise, after fixing up the order of names? If it's a column split though, how are middle names handled to prevent misalignment of first name, (middle name(s)), last name?

Or is the idea here to pull out names? Last name `value.split(" ")[-1]` If so, I couldn't figure it out how to handle the variability of middle names 🌵

**Comment by ostephens** [comment]
I think what we wanted to demonstrate here was the 'Add new column based on this column' functionality. So yes something like value.split(" ")[-1] for family name and value.split(" ")[0] for first names.

However, names are a PITA so this is never going to be perfect. Options I can see:

* Demonstrate the 'Add new column' function in a different way
* Use the imperfect approach
* Use the imperfect approach together with some clever filtering to show how you can isolate specific cases - e.g. custom text facet using value.split(" ").length() to get those of length 2, and do those first, then tackle those of length 3 etc. - the problem with this approach is that it gets difficult (e.g. what to do with the cells that contain a single name, do we know that all length 2 names are family name last?)

The advantage of the last approach is that it may offer an exploration of how names are a pain, and this could be combined with introducing using a remote name parser service later in the lesson or in an advanced lesson.

I'm relaxed about this - do you have a view?

**Comment by ostephens** [comment]
Reviewing comments in #14 again it maybe that we didn't really have in mind whether this was done via 'split' or 'add'. Relevant quote from that thread:

@weaverbel said:
> Also some of the UCSD people were quite excited about the GREL abilities so a more advanced GREL bit would probably be appreciated, e.g. I used a GREL thing to turn two columns into one so I could have a single column for a name instead of forename in one and surname in another. (I copied to another column and then combined.) Really useful thing to show I think as well as showing how to split data up into separate columns. Just my two cents ...
@ostephens replied:
> Exercise 10 (currently in basic functions II) could be changed to include the creation of new columns for family name and first name(s)

It's too long ago to remember exactly what I was thinking, but potentially I was thinking that splitting the values across columns might make more sense than reversing the given/family name order (which is what the exercise currently does)

On this basis I'd suggest if we are going to follow through this suggestion we modify the current exercise so that rather than just reversing the two-part names that include a comma, it instead splits all two part names across columns - I can see this would nicely demonstrate several GREL functions that are v useful. So as follows:

1. Create copy of Authors column so we can work on it while keeping our original data as it is. I'll call this new col Name for this e.g.
2. Isolate two part names (in Name col) by creating a custom text facet based on value.split(" ").length()
3. Isolate two part names *without* a comma (in Name col) in them by creating a custom text facet based on value.contains(",")
4. Use 'split' function on Name col with a whitespace as separator to create a new column containing the second part of each two part name without a comma
5. Isolate two part names *with* a comma  (in Name col) using the existing facets
6. Working in your new column (created by 'split') bring across the first part of names with a comma using cells["Name"].value.split(",")[0]
7. Finally in the Name col tidy up the two part names with a comma using value.split(",")[1]

This demonstrates some nice use of:
* Filtering to isolate a set of records which can be worked on as a whole
* Using multiple facets together
* Writing custom text facets
* Using 'length' for Arrays (something I do quite a bit to understand data structure)
* Using 'split' to create multiple cols from a single col
* Bringing in data from other cols using the cells["col name"] structure (something else I do a lot)

How does that sound?

**Comment by icecjan** [comment]
At our session a few weeks ago, people actually found learning the trick to reverse names useful. So we did an optional challenge to transform the author names to Last name, First name format. I added this to my repo today, I'll send a pull request so you can assess if it's suitable?

**Comment by ostephens** [comment]
Thanks for this @icecjan - just made comments on the PR. I think we should integrate this as part of the overall exercise rather than an optional challenge.

Hope comments are useful - get back to me here or on the PR if you have questions or disagree with any of my comments :)

**Comment by ccronje** [comment]
Thanks @ostephens and @icecjan - I worked through your exercise Owen and tried to flesh out the steps, which took the exercise on a slightly different turn towards the end. See what you think. The Name column still has the commas to play around with, so @icecjan's challenge/solution drop-down could still be added onto the challenge. 

1. Create copy of Authors column so we can work on it while keeping our original data as it is. I'll call this new column 'Name'. On the Authors column select ‘Edit column->Add column based on this column...'. Enter new column name 'Name', GREL expression is `value` (i.e. make no change), click 'Ok'.

2. Isolate the two part names in the 'Name' column by creating a custom text facet. On the Name column select 'Facet->Custom text facet...'. Enter GREL expression `value.split(" ").length()` then select '2' in the facet.

3. Isolate the two part names _without_ a comma in the 'Name' column by creating a second custom text facet. On the Name column select 'Facet->Custom text facet...'. . Enter GREL expression `value.contains(",")` then select 'false' in the facet.

4. Extract the last name from the Name column from names _without_ a comma. On the Name column select  ‘Edit column->Add column based on this column...'. Enter new column name 'Last Name', and GREL expression `value.split(" ")[1]` and click 'Ok'.

5. Extract the first name from the Name column from names _without_ a comma. On the Name column select  ‘Edit column->Add column based on this column...'. Enter new column name 'First Name', and GREL expression `value.split(" ")[0]` and click 'Ok'.

6. Extract the last name from the Name column from names _with_ a comma. Select the 'true' facet (in facet created in Step 3). On the Last Name column select  ‘Edit cells->Transform...'. Enter GREL expression `cells["Name"].value.split(", ")[0]` and click 'Ok'.

7. Extract the first name from the Name column from names _with_ a comma. On the First Name column select  ‘Edit cells->Transform...'. Enter GREL expression `cells["Name"].value.split(", ")[1]` and click 'Ok'.

8. (continues onto next part of challenge with solution drop-down)

**Comment by weaverbel** [comment]
Hey @ccronje Got time to put into the zoom to chat? https://aarnet.zoom.us/j/949264483

**Comment by ccronje** [comment]
Awesome to chat with you @weaverbel thanks for the ping :-)

**Comment by icecjan** [comment]
Hi @ccronje @ostephens thanks for the comments! Sorry for the late reply, been doing other things today. I'm new to collaborating in GitHub so I'm sorry if I submitted a pull request too early! 

Agree with all of the above. The reason I did it as a challenge was that participants at our session loved doing the challenges after they followed the step-by-step exercises, which helps them to remember and understand the steps. I agree with your point re consistency, but other LC sessions have challenges too :)

The above exercise is great! What do we do with the 3,4,5 part names? Is it possible to add another column called "Other names" and extract the 2nd, 3rd, 4th part of the rest of the names to this column? So following @ccronje exercise above:

8. Extract last name from 3, 4, 5 (multi?) part names without commas: Select facet 3, 4, and 5 in facet created in step 2. Select 'false' in facet created in step 3. On the Last name column, select Edit column > Transform. Enter expression cells["Name"].value.split(" ").reverse()[0]

9. Extract first name from 3, 4, 5 part names without commas: On the First name column, Select Edit column > Transform. Enter expression cells["Name"].value.split(" ")[0]

10. Extract Other names: Is there a clever way of extracting everything but the first and last names? 

Is this going to become too long?
