### ISSUE TITLE
When to use/not to use.

### ISSUE THREAD

**Issue by JohnBorghi** [data-lessons/library-openrefine-DEPRECATED#86]
This is based on a conversation here at Berkeley, so credit to @scottcpeterson as well.

As part of the introduction about the uses of OpenRefine, it might be useful also discuss its limitations and when it should be used independently versus in concert with other tools (regex, Python, etc).

**Comment by rjaffe** [comment]
Recently, I used Open Refine to clean values gathered in a Google sheet and then to count the number of times a variety of terms appeared in the sheet. The counting I did by manually faceting two columns and then by filtering on ten or so terms in each column. By the fifth or tenth time I had repeated this exercise (as the spreadsheet changed), I realized that I would be better off to script the process in Python. Of course, Python is a much heavier lift then Open Refine, but it's good to know when to use each.

**Comment by rjaffe** [comment]
Scott shows me that I can use the transformations>reuse  function to "replay" actions.

**Comment by ostephens** [comment]
When I do OpenRefine training (outside LC) I include a short section on other tools where I cover the following:

**Is OpenRefine the right tool?**

- Excel - familiarity, better for data entry, cut and paste operation, no paging to navigate
- Google Spreadsheets - similar to Excel, can get external data relatively easily, easy to collaborate and share Google Fusion Tables - if you just want to filter, easy to share
- Text editor - powerful text editor can do many things
- Unix tools - more challenging to use, but quick and some things (finding things, sorting) are easy
- Writing code - most sophisticated and most to learn!

I talk through these in a bit more detail, but what I've not got is examples of specific problems which might solve in OR/other tools

**Comment by ccronje** [comment]
Agree it's important to talk about each tools' strengths and weaknesses. Good to be flexible.

@rjaffe wrt first comment, were you looking for specific terms? Would `value.contains("term")` have been useful? Or were you exploring? Would `Facet > Customized facet > Word facet` have helped?

**Comment by jmjamison** [comment]
About "transformations>reuse function to "replay" actions".  Might be had to locate for new user.  Maybe a walk through example would help.  (Helpful but I didn't realize it was there till I read this issue.)

**Comment by rjaffe** [comment]
@ccronje I was trying to count the number of times a specific term appeared. So, value.contains("term") successfully modifies the value in the field to True or False. The next step would be to count the number of True values. Then @jmjamison  to repeat in an automated manner for 10 or so terms in each of two columns. 

Background: In a spreadsheet about consulting or reference cases dealing with sensitive research data, we have a column titled "regulatory" which lists the scheme(s) that controls the particular set of data. Values include 'data use agreement,' 'human subjects', 'hipaa', etc.  Some cases involve more than one regulatory tag, for example: 'data use agreement, human subjects'. Open Refine was great for cleaning up extra spaces and other typographic errors. The question here: Is it feasible to do the counting iteratively (or at all) in Open Refine, or better to switch to a different tool?

**Comment by rjaffe** [comment]
Perhaps the lesson outcome is: clean the data, export to a csv, and do the counting in the BASH shell. That would add a nice arc to the day.

**Comment by ostephens** [comment]
I suspect you could do the counting in OpenRefine but I'm not sure I've quite got my head around your use case - if you are interested in digging into this post an made up example with some dummy data and I'll have a look.

Agreed that export then use in another tool would be nice link to other lessons, but I think we need to keep them separate as we can't always assume that lessons will happen in a particular order, or that specific lessons will be taught during the same workshop

**Comment by rjaffe** [comment]
Thanks Owen, Jamie and Carmi! Here's a test data set to illustrate. Have a good weekend!\

[Reference-Consultations-Sensitive-Research-Data-TESTDATA.csv.zip](https://github.com/data-lessons/library-openrefine/files/1049184/Reference-Consultations-Sensitive-Research-Data-TESTDATA.csv.zip)

**Comment by rjaffe** [comment]
Scott points out that Facet > Customized Facet > Word Facet will give me count of individual tags.

**Comment by ostephens** [comment]
@rjaffe so does that Word Facet give you exactly what you want?

If you want to count across both columns together, you can use a "Custom Text Facet" with GREL like:

`(cells["Regulatory tags"].value + " " + cells["Data Activity tags"].value).replace(/\n/," ").split(" ")`

Or if you wanted to know how often two terms appeared across the two columns the rather more complicated:

`forEach(cells["Regulatory tags"].value.replace(/\n/," ").split(" "),v, forEach(cells["Data Activity tags"].value.replace(/\n/," ").split(" "),w,v+" && "+w))[0]`

Note that this latter counts occurrences of each combination - so single rows end up being counted multiple times because they represent multiple combinations of Regulatory/Data Activity tags if that makes sense.

Anyway - lots of options here! Another part of the question of using a different tool is how much work it is to transfer the data between the tools you want to use.

Final note there are two options for using OpenRefine with Python - so it may not be a matter of one or the other, but both! :

1. You can write any transformations or Custom Text Facet in Python inside OpenRefine if you want. See https://github.com/OpenRefine/OpenRefine/wiki/Jython#tutorial---working-with-phone-numbers-using-java-libraries-inside-python for an example 
2. You can script OpenRefine processes end-to-end from Python - Load data; Apply transforms; Export data - and then go on to analyse if you want - see https://github.com/PaulMakepeace/refine-client-py

**Comment by ostephens** [comment]
Oh and finally finally just to check you know that when you have a facet that does the sort of counting you want, you can get a cut/pastable table of the facet values and counts by clicking on the 'xx headings' link at the top left of the facet panel
